/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Bases */
        get: operations["list_knowledge_bases_api_v1_knowledge_bases_get"];
        put?: never;
        /** Create Knowledge Base */
        post: operations["create_knowledge_base_api_v1_knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Base */
        get: operations["get_knowledge_base_api_v1_knowledge_bases__knowledge_base_id__get"];
        put?: never;
        post?: never;
        /** Delete Knowledge Base */
        delete: operations["delete_knowledge_base_api_v1_knowledge_bases__knowledge_base_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Document Versions */
        get: operations["list_document_versions_api_v1_knowledge_bases__knowledge_base_id__documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_knowledge_bases__knowledge_base_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/documents/{version_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Document Ingestion */
        post: operations["retry_document_ingestion_api_v1_knowledge_bases__knowledge_base_id__documents__version_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/documents/{document_id}/versions/{version_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Source */
        get: operations["get_document_source_api_v1_knowledge_bases__knowledge_base_id__documents__document_id__versions__version_id__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_v1_knowledge_bases__knowledge_base_id__conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_v1_knowledge_bases__knowledge_base_id__conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/conversations/{conversation_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__questions_get"];
        put?: never;
        /** Create Question */
        post: operations["create_question_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/conversations/{conversation_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Answers */
        get: operations["list_answers_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__answers_get"];
        put?: never;
        /** Stream Answer */
        post: operations["stream_answer_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-bases/{knowledge_base_id}/conversations/{conversation_id}/answers/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Answer */
        post: operations["cancel_answer_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__answers__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerCancellationResponse */
        AnswerCancellationResponse: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "cancel_requested" | "cancelled" | "completed" | "failed";
        };
        /** AnswerCancelledEvent */
        AnswerCancelledEvent: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: "1";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cancelled";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** AnswerDeltaEvent */
        AnswerDeltaEvent: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: "1";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Delta */
            delta: string;
        };
        /** AnswerErrorEvent */
        AnswerErrorEvent: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: "1";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        AnswerEvent: components["schemas"]["AnswerStatusEvent"] | components["schemas"]["AnswerDeltaEvent"] | components["schemas"]["AnswerFinalEvent"] | components["schemas"]["AnswerRefusalEvent"] | components["schemas"]["AnswerErrorEvent"] | components["schemas"]["AnswerCancelledEvent"];
        /** AnswerFinalEvent */
        AnswerFinalEvent: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: "1";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "final";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationResponse"][];
        };
        /** AnswerHistoryItem */
        AnswerHistoryItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Question Content */
            question_content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "cancel_requested" | "cancelled" | "completed" | "failed";
            /** Outcome */
            outcome: ("answered" | "refused") | null;
            /** Answer */
            answer: string | null;
            /** Refusal Code */
            refusal_code: string | null;
            /** Refusal Message */
            refusal_message: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Failure Message */
            failure_message: string | null;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Retrieval Version */
            retrieval_version: string;
            /** Retrieval Query */
            retrieval_query: string;
            /** Query Rewrite Version */
            query_rewrite_version: string;
            /** Evidence Assessment Prompt Version */
            evidence_assessment_prompt_version: string;
            /** Citation Repair Prompt Version */
            citation_repair_prompt_version: string;
            /** Workflow Version */
            workflow_version: string;
            workflow_trace: components["schemas"]["AnswerWorkflowTrace"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Citations */
            citations: components["schemas"]["CitationResponse"][];
        };
        /** AnswerHistoryResponse */
        AnswerHistoryResponse: {
            /** Items */
            items: components["schemas"]["AnswerHistoryItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AnswerRefusalEvent */
        AnswerRefusalEvent: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: "1";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "refusal";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Content */
            content: string;
        };
        /** AnswerStatusEvent */
        AnswerStatusEvent: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: "1";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "status";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "retrieving" | "generating";
        };
        /** AnswerWorkflowTrace */
        AnswerWorkflowTrace: {
            /** Retrieval Plan Version */
            retrieval_plan_version?: string | null;
            /** Retrieval Queries */
            retrieval_queries?: string[];
            /** Retrieval Rounds */
            retrieval_rounds?: components["schemas"]["WorkflowRetrievalRoundTrace"][];
            /** Assessments */
            assessments?: components["schemas"]["WorkflowEvidenceAssessmentTrace"][];
            /** Citation Validations */
            citation_validations?: components["schemas"]["WorkflowCitationValidationTrace"][];
            /**
             * Supplemental Retrieval Attempts
             * @default 0
             */
            supplemental_retrieval_attempts: number;
            /**
             * Citation Repair Attempts
             * @default 0
             */
            citation_repair_attempts: number;
        };
        /** Body_upload_document_api_v1_knowledge_bases__knowledge_base_id__documents_post */
        Body_upload_document_api_v1_knowledge_bases__knowledge_base_id__documents_post: {
            /** File */
            file: string;
        };
        /** CitationResponse */
        CitationResponse: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Document Version Id */
            document_version_id: string;
            /** Document Name */
            document_name: string;
            /** Page Number */
            page_number: number;
            /** Excerpt */
            excerpt: string;
            /** Source Url */
            source_url: string;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title: string;
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Name */
            name: string;
            /** Version Number */
            version_number: number;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Page Count */
            page_count: number;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Attempt Count */
            attempt_count: number;
            /** Retryable */
            retryable: boolean;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deduplicated */
            deduplicated: boolean;
            /** Request Id */
            request_id: string;
        };
        /** DocumentVersionItem */
        DocumentVersionItem: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Name */
            name: string;
            /** Version Number */
            version_number: number;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Page Count */
            page_count: number;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Attempt Count */
            attempt_count: number;
            /** Retryable */
            retryable: boolean;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentVersionListResponse */
        DocumentVersionListResponse: {
            /** Items */
            items: components["schemas"]["DocumentVersionItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Instance */
            instance: string;
            /** Code */
            code: string;
            /** Request Id */
            request_id: string;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Code */
            code: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** IngestionRetryResponse */
        IngestionRetryResponse: {
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Attempt Count */
            attempt_count: number;
            /** Retryable */
            retryable: boolean;
            /** Failure Code */
            failure_code?: string | null;
        };
        /** KnowledgeBaseCreate */
        KnowledgeBaseCreate: {
            /** Name */
            name: string;
        };
        /** KnowledgeBaseListResponse */
        KnowledgeBaseListResponse: {
            /** Items */
            items: components["schemas"]["KnowledgeBaseResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** KnowledgeBaseResponse */
        KnowledgeBaseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /** Content */
            content: string;
        };
        /** QuestionListResponse */
        QuestionListResponse: {
            /** Items */
            items: components["schemas"]["QuestionResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** QuestionResponse */
        QuestionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checks */
            checks: {
                [key: string]: "ok" | "unavailable";
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowCitationValidationTrace */
        WorkflowCitationValidationTrace: {
            /** Valid */
            valid: boolean;
            /**
             * Issue
             * @enum {string}
             */
            issue: "empty_answer" | "uncited_claim" | "unknown_label" | "valid";
        };
        /** WorkflowEvidenceAssessmentTrace */
        WorkflowEvidenceAssessmentTrace: {
            /** Sufficient */
            sufficient: boolean;
            /** Selected Chunk Ids */
            selected_chunk_ids: string[];
            /** Supplemental Query */
            supplemental_query: string | null;
        };
        /** WorkflowFusedCandidateTrace */
        WorkflowFusedCandidateTrace: {
            /** Chunk Id */
            chunk_id: string;
            /** Fused Score */
            fused_score: number;
            /** Best Raw Cosine Score */
            best_raw_cosine_score: number;
            /** Reranker Score */
            reranker_score?: number | null;
            /** Reranked Rank */
            reranked_rank?: number | null;
            /** Selected As Primary */
            selected_as_primary: boolean;
        };
        /** WorkflowQueryRetrievalTrace */
        WorkflowQueryRetrievalTrace: {
            /** Query */
            query: string;
            /** Candidates */
            candidates: components["schemas"]["WorkflowRetrievalCandidateTrace"][];
        };
        /** WorkflowRerankerTrace */
        WorkflowRerankerTrace: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Revision */
            revision: string;
            /** Config Version */
            config_version: string;
        };
        /** WorkflowRetrievalCandidateTrace */
        WorkflowRetrievalCandidateTrace: {
            /** Chunk Id */
            chunk_id: string;
            /** Raw Rank */
            raw_rank: number;
            /** Raw Cosine Score */
            raw_cosine_score: number;
        };
        /** WorkflowRetrievalRoundTrace */
        WorkflowRetrievalRoundTrace: {
            /** Round Number */
            round_number: number;
            /** Queries */
            queries: string[];
            /** Query Results */
            query_results: components["schemas"]["WorkflowQueryRetrievalTrace"][];
            /** Fused Candidates */
            fused_candidates: components["schemas"]["WorkflowFusedCandidateTrace"][];
            /** Final Evidence Chunk Ids */
            final_evidence_chunk_ids: string[];
            /** Rrf Rank Constant */
            rrf_rank_constant: number;
            reranker?: components["schemas"]["WorkflowRerankerTrace"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_knowledge_bases_api_v1_knowledge_bases_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_knowledge_base_api_v1_knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_knowledge_base_api_v1_knowledge_bases__knowledge_base_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_knowledge_base_api_v1_knowledge_bases__knowledge_base_id__delete: {
        parameters: {
            query: {
                confirm: boolean;
            };
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_document_versions_api_v1_knowledge_bases__knowledge_base_id__documents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_document_api_v1_knowledge_bases__knowledge_base_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_knowledge_bases__knowledge_base_id__documents_post"];
            };
        };
        responses: {
            /** @description Exact duplicate resolved to the existing document version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_document_ingestion_api_v1_knowledge_bases__knowledge_base_id__documents__version_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRetryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_document_source_api_v1_knowledge_bases__knowledge_base_id__documents__document_id__versions__version_id__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_knowledge_bases__knowledge_base_id__conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_conversation_api_v1_knowledge_bases__knowledge_base_id__conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_conversation_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_questions_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__questions_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                knowledge_base_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_question_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_answers_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__answers_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                knowledge_base_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerHistoryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_answer_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Versioned answer event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AnswerEvent"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_answer_api_v1_knowledge_bases__knowledge_base_id__conversations__conversation_id__answers__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_base_id: string;
                conversation_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerCancellationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
