"""create knowledge bases

Revision ID: 76b49e159f56
Revises:
Create Date: 2026-07-25 17:24:15.124030
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "76b49e159f56"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_bases",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
    )
    op.create_index(
        "uq_knowledge_bases_name_ci",
        "knowledge_bases",
        [sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_knowledge_bases_name_ci", table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    # ### end Alembic commands ###
